CREATE TABLE DACCOUNT
(
	ID VARCHAR(36) PRIMARY KEY,
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	NAME NVARCHAR(255),
	EMAIL NVARCHAR(255),
	PHONE VARCHAR(10),
	DATEOFBIRTH DATE,
	AVATAR VARCHAR(255),
	TIMECREATED DATETIME
)
GO
CREATE TABLE TNOTIFICATION
(
	ID VARCHAR(36) PRIMARY KEY,
	DACCOUNTID_SEND VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	DACCOUNTID_RECEIVE VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	TYPE INT,
	WATCHED INT,
	MESSAGE NVARCHAR(MAX),
	TIMECREATED DATETIME
)
GO
CREATE TABLE TMESSAGE
(
	ID VARCHAR(36) PRIMARY KEY,
	DACCOUNTID_SEND VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	DACCOUNTID_RECEIVE VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	WATCHED INT,
	MESSAGE NVARCHAR(MAX),
	TIMECREATED DATETIME
)
GO
CREATE TABLE TFRIENDREQUEST
(
	ID VARCHAR(36) PRIMARY KEY,
	DACCOUNTID_SEND VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	DACCOUNTID_RECEIVE VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	STATUS INT,
	MESSAGE NVARCHAR(MAX),
	TIMECREATED DATETIME
)
GO
CREATE TABLE TFRIEND
(
	ID VARCHAR(36) PRIMARY KEY,
	DACCOUNTID VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	DFRIENDID VARCHAR(36) FOREIGN KEY REFERENCES DACCOUNT(ID),
	TIMECREATED DATETIME
)